version: '3.7'

services:
  
  app:
    container_name: app_container
    build: .
    restart: always
    command: "python main.py"
    ports:
      - 8085:8000
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    
# networks:
#   default:
#     external: false
#     name: downstream_bridge
