FROM python:3.8-slim
LABEL authors="gigatech"
ENV PYTHONUNBUFFERED=1

WORKDIR /app

RUN apt-get update\
    && apt-get install gcc -y\
    && apt-get clean

COPY . /app

RUN pip3 install --upgrade pip
RUN pip3 install -r requirements.txt

EXPOSE 8000

ENTRYPOINT ["uvicorn"]
CMD ["app.main:app", "--host", "0.0.0.0", "--port", "8000"]